/*
 * This source file was generated by the Gradle 'init' task
 */
package testcar;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testCarInitialization() {
        Car car = new Car("BMW", "White", 200, 10.0f, 50.0f, 0.2f, 0);

        // ตรวจสอบค่าเริ่มต้น
        assertEquals("BMW", car.getBrand());
        assertEquals("White", car.getColor());
        assertEquals(0, car.getCurrentSpeed()); // ความเร็วเริ่มต้นควรเป็น 0
        assertEquals(50.0f, car.getMaxFuel()); // ความจุถังน้ำมันควรเป็น 50 ลิตร
    }

    @Test
    void testCarDrivingAndRefueling() {
        Car car = new Car("BMW", "White", 200, 10.0f, 50.0f, 0.2f, 0);

        // ขับรถและตรวจสอบน้ำมัน
        car.driveCar(60); // ขับรถ 60 นาที
        assertEquals(8.0f, car.getFuel(), 0.01f); // น้ำมันควรลดลงเหลือ 8 ลิตร

        // เติมน้ำมันและตรวจสอบ
        car.addFuel(20); // เติมน้ำมัน 20 ลิตร
        assertEquals(30.0f, car.getFuel(), 0.01f); // น้ำมันควรเป็น 30 ลิตร
    }
}
